version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/server
hooks:
  AfterInstall:
    - location: scripts/copy.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
      runas: root