version: "3"

services:
  was8080:
    container_name: was-8080
    image: .
    ports:
      - 8080:8080
    environment:
      TZ: "Asia/Seoul"
    volumes:
        - /home/ubuntu/deploy.log:/home/ubuntu/deploy.log
        - /home/ubuntu/server/src/main/resources:/home/ubuntu/server/src/main/resources

  was8081:
    container_name: was-8081
    image: .
    ports:
      - 8081:8080
    environment:
      TZ: "Asia/Seoul"
    volumes:
      - /home/ubuntu/deploy.log:/home/ubuntu/deploy.log
      - /home/ubuntu/server/src/main/resources:/home/ubuntu/server/src/main/resources

  nginx:
    container_name: nginx
    image: nginx:1.14
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/nginx/service-url.inc:/etc/nginx/service-url.inc
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - /home/ubuntu/frontend/build:/home/ubuntu/frontend/build