version: "3"

services:
  springboot:
    container_name: sgsg-application
    environment:
      TZ: "Asia/Seoul"
    image: sagak/server:latest
    volumes:
      - /home/ubuntu/deploy.log:/home/ubuntu/deploy.log

  nginx:
    container_name: nginx
    image: nginx:1.14
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - /home/ubuntu/frontend/build:/home/ubuntu/frontend/build