server:
  http2:
    enabled: true
auth:
  encrypt:
    seed: B95D645620C482160DF37A0F6681800875FC3E0E07DEBC6687C4E9237689C013

---
spring:
  config:
    activate:
      on-profile: develop
---

spring:
  config:
    activate:
      on-profile: production