spring:
  profiles:
    include: auth, app, mail, db
debug: true
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR
---
spring:
  config:
    activate:
      on-profile: develop
debug: false
---
spring:
  config:
    activate:
      on-profile: production
debug: false