spring:
  profiles:
    include: auth
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;IFEXISTS=FALSE;
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
debug: true


---
spring:
  config:
    activate:
      on-profile: develop
---

spring:
  config:
    activate:
      on-profile: production