spring:
  profiles:
    include: auth
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;IFEXISTS=FALSE;
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
debug: true

paging:
  folder:
    limit: 20
    max_limit: 50
    min_page: 1
  memo:
    limit: 20
    max_limit: 50
    min_page: 1


logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR
---
spring:
  config:
    activate:
      on-profile: develop
---

spring:
  config:
    activate:
      on-profile: production