name: CI
on:
  pull_request:
    branches:
      - 'develop'
  push:
    branches:
      - 'chore/**'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Github 업스트림 체크아웃
        uses: actions/checkout@v2

      - name: Github 서브모듈 체크아웃
        uses: actions/checkout@v2
        with:
          repository: hongbin-dev/sgsg-private
          token: ${{ secrets.SGSG_PRIVATE_PAT }}
          path: src/main/resources/config

      - name: JDK 11 설치
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.8

      - name: ./gradlew 권한 설정
        run: chmod +x gradlew

      - name: 빌드
        run: ./gradlew build